const card = [
  {
    id: 1,
    title: "Jordan 1's",
    img: "data:image/webp;base64,...",
    price: "$120+",
    inStock: true,
    created: 1985,
    rating: 4.86,
    colorway: "Chicago",
    releaseDate: "1985-09-15",
    brand: "Nike",
    category: "Basketball"
  },
  {
    id: 2,
    title: "Jordan 2's",
    img: "data:image/webp;base64,...",
    price: "$110+",
    inStock: false,
    created: 1986,
    rating: 4.5,
    colorway: "White/Red",
    releaseDate: "1986-11-01",
    brand: "Nike",
    category: "Basketball"
  },
  {
    id: 3,
    title: "Jordan 3's",
    img: "data:image/webp;base64,...",
    price: "$150+",
    inStock: true,
    created: 1988,
    rating: 4.7,
    colorway: "White/Cement",
    releaseDate: "1988-02-06",
    brand: "Nike",
    category: "Basketball"
  },
  {
    id: 4,
    title: "Jordan 4's",
    img: "data:image/webp;base64,...",
    price: "$160+",
    inStock: true,
    created: 1989,
    rating: 4.6,
    colorway: "Bred",
    releaseDate: "1989-02-17",
    brand: "Nike",
    category: "Basketball"
  },
  {
    id: 5,
    title: "Jordan 5's",
    img: "data:image/webp;base64,...",
    price: "$170+",
    inStock: false,
    created: "1990",
    rating: 4.4,
    colorway: "Fire Red",
    releaseDate: "1990-02-01",
    brand: "Nike",
    category: "Basketball"
  },
  {
    id: 6,
    title: "Jordan 6's",
    img: "data:image/webp;base64,...",
    price: "$180+",
    inStock: true,
    created: "1991",
    rating: 4.5,
    colorway: "Infrared",
    releaseDate: "1991-02-01",
    brand: "Nike",
    category: "Basketball"
  },
  {
    id: 7,
    title: "Jordan 7's",
    img: "data:image/webp;base64,...",
    price: "$160+",
    inStock: false,
    created: "1992",
    rating: 4.3,
    colorway: "Hare",
    releaseDate: "1992-05-01",
    brand: "Nike",
    category: "Basketball"
  },
  {
    id: 8,
    title: "Jordan 8's",
    img: "data:image/webp;base64,...",
    price: "$190+",
    inStock: true,
    created: "1993",
    rating: 4.6,
    colorway: "Aqua",
    releaseDate: "1993-02-01",
    brand: "Nike",
    category: "Basketball"
  },
  {
    id: 9,
    title: "Jordan 9's",
    img: "data:image/webp;base64,...",
    price: "$200+",
    inStock: true,
    created: "1993",
    rating: 4.5,
    colorway: "White/Black",
    releaseDate: "1993-11-01",
    brand: "Nike",
    category: "Basketball"
  },
  {
    id: 10,
    title: "Jordan 10's",
    img: "data:image/webp;base64,...",
    price: "$175+",
    inStock: true,
    created: "1994",
    rating: 4.4,
    colorway: "Chicago",
    releaseDate: "1994-11-01",
    brand: "Nike",
    category: "Basketball"
  },
  {
    id: 11,
    title: "Jordan 11's",
    img: "data:image/webp;base64,...",
    price: "$220+",
    inStock: false,
    created: "1995",
    rating: 4.8,
    colorway: "Concord",
    releaseDate: "1995-11-10",
    brand: "Nike",
    category: "Basketball"
  },
  {
    id: 12,
    title: "Jordan 12's",
    img: "data:image/webp;base64,...",
    price: "$200+",
    inStock: true,
    created: "1996",
    rating: 4.5,
    colorway: "Flu Game",
    releaseDate: "1996-11-01",
    brand: "Nike",
    category: "Basketball"
  },
  {
    id: 13,
    title: "Adidas Ultraboost 1.0",
    img: "data:image/webp;base64,...",  
    price: "$135",
    inStock: true,
    created: "2015",              // approximate first release year
    rating: 4.7,                  // from product listing  
    colorway: "Triple Black",
    releaseDate: "2015-03-01",
    brand: "Adidas",
    category: "Running"
  },
  {
    id: 14,
    title: "Adidas Superstar II",
    img: "data:image/webp;base64,...",
    price: "$100",
    inStock: true,
    created: "1970s",             // original era
    rating: 4.8,
    colorway: "Core White / Black",
    releaseDate: "1970-10-01",
    brand: "Adidas",
    category: "Lifestyle"
  },
  {
    id: 15,
    title: "Adidas Grand Court 2.0 (Women)",
    img: "data:image/webp;base64,...",
    price: "$42",
    inStock: true,
    created: "2020s",
    rating: 4.7,
    colorway: "Cloud White / Core Black",
    releaseDate: "2020-06-01",
    brand: "Adidas",
    category: "Casual"
  },
  {
    id: 16,
    title: "Adidas Grand Court 2.0 (Men)",
    img: "data:image/webp;base64,...",
    price: "$34.30",
    inStock: true,
    created: "2020s",
    rating: 4.8,
    colorway: "Cloud White / Core Black",
    releaseDate: "2020-06-01",
    brand: "Adidas",
    category: "Casual"
  },
  {
    id: 17,
    title: "Adidas Campus 00s",
    img: "data:image/webp;base64,...",
    price: "$79.99",
    inStock: true,
    created: "2000s (retro revamp)",
    rating: 4.9,
    colorway: "Wonder White / Cloud White",
    releaseDate: "2022-01-01",
    brand: "Adidas",
    category: "Skate / Casual"
  },
  {
    id: 18,
    title: "Adidas Swift Run 1.0",
    img: "data:image/webp;base64,...",
    price: "$60",
    inStock: true,
    created: "mid-2010s",
    rating: 4.4,
    colorway: "Core Black / Core Black",
    releaseDate: "2017-05-01",
    brand: "Adidas",
    category: "Lifestyle / Running"
  },
  {
    id: 19,
    title: "Adidas Gazelle Indoor",
    img: "data:image/webp;base64,...",
    price: "$96",
    inStock: true,
    created: "1960s",
    rating: 3.6,
    colorway: "Legacy Gold / Cloud White",
    releaseDate: "1966-05-01",
    brand: "Adidas",
    category: "Indoor / Casual"
  },
  {
    id: 20,
    title: "Adidas Sambae",
    img: "data:image/webp;base64,...",
    price: "$110",
    inStock: true,
    created: "modern reinterpretation",
    rating: 4.6,
    colorway: "Core Black / Cloud White",
    releaseDate: "2022-08-01",
    brand: "Adidas",
    category: "Heritage / Casual"
  },
  {
    id: 21,
    title: "Adidas Breaknet Sleek",
    img: "data:image/webp;base64,...",
    price: "$65",
    inStock: true,
    created: "2020s",
    rating: 4.5,
    colorway: "Cloud White / Cloud White",
    releaseDate: "2021-03-01",
    brand: "Adidas",
    category: "Lifestyle"
  },
  {
    id: 22,
    title: "Adidas Lite Racer Adapt 7.0",
    img: "data:image/webp;base64,...",
    price: "$70",
    inStock: true,
    created: "2020s",
    rating: 4.2,
    colorway: "Core Black / Core Black",
    releaseDate: "2021-07-01",
    brand: "Adidas",
    category: "Slip‑On / Casual"
  },
  {
    id: 23,
    title: "Adidas VL Court 3.0",
    img: "data:image/webp;base64,...",
    price: "$57",
    inStock: true,
    created: "2020s",
    rating: 4.8,
    colorway: "Cloud White / Footwear White",
    releaseDate: "2020-09-01",
    brand: "Adidas",
    category: "Street / Casual"
  },
  {
    id: 24,
    title: "Adidas Grand Court Alpha",
    img: "data:image/webp;base64,...",
    price: "$80",
    inStock: true,
    created: "2000s",
    rating: 4.9,
    colorway: "Core Black / Footwear White",
    releaseDate: "2005-04-01",
    brand: "Adidas",
    category: "Skate / Street"
  },

    {
    id: 25,
    title: "New Balance 740",
    img: "data:image/webp;base64,...",
    price: "$114.99",
    inStock: true,
    created: "2000s (revived)",
    rating: 4.5,
    colorway: "Black / Grey",
    releaseDate: "2024-10-01",
    brand: "New Balance",
    category: "Lifestyle / Retro"
  },
  {
    id: 26,
    title: "New Balance 530",
    img: "data:image/webp;base64,...",
    price: "$109.99",
    inStock: true,
    created: "1992",
    rating: 4.7,
    colorway: "White / Natural Indigo",
    releaseDate: "2023-08-01",
    brand: "New Balance",
    category: "Dad / Casual"
  },
  {
    id: 27,
    title: "New Balance 327",
    img: "data:image/webp;base64,...",
    price: "$104.99",
    inStock: true,
    created: "2020",
    rating: 4.5,
    colorway: "Beige / Gum",
    releaseDate: "2021-03-01",
    brand: "New Balance",
    category: "Lifestyle"
  },
  {
    id: 28,
    title: "New Balance 574",
    img: "data:image/webp;base64,...",
    price: "$99.99",
    inStock: true,
    created: "1988",
    rating: 4.5,
    colorway: "Grey / Navy",
    releaseDate: "1988-06-01",
    brand: "New Balance",
    category: "Classic / Retro"
  },
  {
    id: 29,
    title: "New Balance 1906R",
    img: "data:image/webp;base64,...",
    price: "$154.99",
    inStock: true,
    created: "2010s (revived 2022)",
    rating: 3.8,
    colorway: "Black / Grey",
    releaseDate: "2022-09-01",
    brand: "New Balance",
    category: "Tech / Futuristic"
  },
  {
    id: 30,
    title: "New Balance 9060",
    img: "data:image/webp;base64,...",
    price: "$159.99",
    inStock: true,
    created: "2023",
    rating: 4.5,
    colorway: "White / Grey / Blue",
    releaseDate: "2023-05-01",
    brand: "New Balance",
    category: "Y2K / Chunky"
  },
  {
    id: 31,
    title: "New Balance 550 (Women)",
    img: "data:image/webp;base64,...",
    price: "$79.99",
    inStock: true,
    created: "1989 (revived)",
    rating: 4.2,
    colorway: "Rain Cloud / White",
    releaseDate: "2022-01-01",
    brand: "New Balance",
    category: "Heritage / Basketball"
  },
  {
    id: 32,
    title: "New Balance 550 (Men)",
    img: "data:image/webp;base64,...",
    price: "$109.99",
    inStock: true,
    created: "1989 (revived)",
    rating: 4.3,
    colorway: "White / Grey",
    releaseDate: "2022-01-01",
    brand: "New Balance",
    category: "Heritage / Basketball"
  },
  {
    id: 33,
    title: "New Balance 2002R",
    img: "data:image/webp;base64,...",
    price: "$144.99",
    inStock: true,
    created: "2010 (revived)",
    rating: 4.7,
    colorway: "Grey / Silver",
    releaseDate: "2022-06-01",
    brand: "New Balance",
    category: "Runner / Lifestyle"
  },
  {
    id: 34,
    title: "New Balance 480",
    img: "data:image/webp;base64,...",
    price: "$99.99",
    inStock: true,
    created: "1980s",
    rating: 4.6,
    colorway: "White / Blue",
    releaseDate: "2023-09-01",
    brand: "New Balance",
    category: "Basketball / Lifestyle"
  },
  {
    id: 35,
    title: "New Balance Fresh Foam 680v8",
    img: "data:image/webp;base64,...",
    price: "$79.99",
    inStock: true,
    created: "2024",
    rating: 4.4,
    colorway: "Black / White",
    releaseDate: "2024-01-01",
    brand: "New Balance",
    category: "Running / Training"
  },
  {
    id: 36,
    title: "New Balance Fresh Foam X 1080v14",
    img: "data:image/webp;base64,...",
    price: "$164.99",
    inStock: true,
    created: "2025",
    rating: 4.7,
    colorway: "Grey / Lime",
    releaseDate: "2025-04-01",
    brand: "New Balance",
    category: "High Performance / Running"
  }
]

function inject(item){

  DOMSelectors.display.insertAdjacentHTML(
    "afterbegin",
    `<div class="display-card">
      <img class="display-img" src="${item.img}"/>
      <h2 class="display-brand">${item.brand}</h2>
      <h3 class="display-brand">${item.title}</h3>
      <button class="remove btn">Remove Card</button>
    </div>`
  );
}

inject(card[0]);